# Use official Golang image
FROM golang:1.23.1

# Set the working directory
WORKDIR /app

# Copy the Go module files and install dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the application
RUN go build -o etl-service ./cmd/main.go

# Expose the application port (if needed)
EXPOSE 8080

# Run the service
CMD ["./etl-service"]
